Docker images update to sync dev and prod and more

diff --git a/scripts/ci-backend-test-acceptance b/scripts/ci-backend-test-acceptance
--- a/scripts/ci-backend-test-acceptance
+++ b/scripts/ci-backend-test-acceptance
@@ -14,11 +14,13 @@ echo $SECONDS seconds elapsed
 log-header "Preparing execution environment: Prepare PHP config, application & composer dev dependencies"
 SECONDS=0
 # configure path to application
-sed -i "s#/app#$CI_PROJECT_DIR#g" /usr/local/etc/php-fpm.d/fpm.conf
+# *https://forums.docker.com/t/sed-couldnt-open-temporary-file-xyz-permission-denied-when-using-virtiofs/125473/2
+sed "s#/app#$CI_PROJECT_DIR#g" /usr/local/etc/php-fpm.d/fpm.conf > tmp; cat tmp > /usr/local/etc/php-fpm.d/fpm.conf; rm tmp
 # let PHP-FPM run as root
-sed -i "s#www-data#root#g" /usr/local/etc/php-fpm.d/fpm.conf
+# sed -i "s#www-data#root#g" /usr/local/etc/php-fpm.d/fpm.conf
 # disable xdebug
-rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
+# rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
+
 bin/console foodsharing:setup
 # also install dev packages
 composer install --prefer-dist --no-progress --no-interaction --no-scripts --ignore-platform-reqs && composer outdated --direct
@@ -43,7 +45,7 @@ echo
 log-header "Running tests"
 failed=0
 SECONDS=0
-vendor/bin/codecept run --xml=report-0.xml --html=report-0.html || failed=1
+vendor/bin/codecept run acceptance --xml=report-acceptance-0.xml --html=report-acceptance-0.html || failed=1
 echo $SECONDS seconds elapsed
 
 if [ $failed -eq 0 ] # first run succeeded, we can finish early
@@ -57,13 +59,13 @@ do
   log-header "Check for codeception errors"
   # check if codeception generated a report file that contains failed tests
   # Otherwise, codeception probably failed itself and the whole job should fail
-  grep -E '<error|<failure' tests/_output/report-$((failed - 1)).xml || \
+  grep -E '<error|<failure' tests/_output/report-acceptance-$((failed - 1)).xml || \
     (echo "report.xml is incomplete, aborting" && false)
 
   log-header "Rerunning failed tests"
   SECONDS=0
   # create separate report files for each re-run so we don't overwrite the previous reports
-  if vendor/bin/codecept run --xml=report-$failed.xml --html=report-$failed.html -g failed;
+  if vendor/bin/codecept run --xml=report-acceptance-$failed.xml --html=report-acceptance-$failed.html -g failed;
   then
     log-header "Done!"
     exit 0
diff --git a/scripts/clean b/scripts/clean
--- a/scripts/clean
+++ b/scripts/clean
@@ -1,28 +1,37 @@
 #!/bin/bash
-
-export CURRENT_USER=$(id -u):$(id -g)
-
-set -o errexit
-
 dir=$(dirname "$0")
-
-base_dir=$(cd "$dir/.." && pwd)
 
 # shellcheck source=./__helping-functions.sh
 source "$dir"/__helping-functions.sh
 
-# Remove docker dev containers
-FS_ENV=dev
-"$dir"/containers-remove
-# Remove docker test containers
-FS_ENV="test"
-"$dir"/containers-remove
+# ENVS
+export FS_ENV=dev
+export CURRENT_USER=$(id -u):$(id -g)
+
+# set -o errexit tells the shell to exit as soon as a command exits with non-zero status, i.e. fails
+set -o errexit
+
+# existsTestEnv=$($dir/docker-compose ls --filter=name='foodsharing' | grep 'foodsharing_test')
+# echo $($dir/docker-compose ls --filter=name='foodsharing_test' | grep 'foodsharing_test')
+
+log-header "Removing containers and images"
+if [[ ! $($dir/docker-compose ls --filter=name='foodsharing' --all | grep 'foodsharing_test') ]];
+then
+  "$dir"/docker-compose down --rmi all -v --remove-orphans
+else
+  FS_ENV="dev"
+  "$dir"/docker-compose down -v --remove-orphans
+  FS_ENV="test"
+  "$dir"/docker-compose down --rmi all -v --remove-orphans
+fi
 
 log-header "Removing local node_modules"
 find $base_dir -name "node_modules" -type d -prune | xargs du -chs # prints the folders
 find $base_dir -name "node_modules" -type d -prune -exec rm -rf '{}' + # removes the folders
 
 log-header "Removing directories"
+
+base_dir=$(cd "$dir/.." && pwd)
 rm -vrf \
   "$base_dir"/assets \
   "$base_dir"/images \
diff --git a/scripts/test-js b/scripts/test-js
--- a/scripts/test-js
+++ b/scripts/test-js
@@ -1,16 +1,15 @@
 #!/bin/bash
-
-export FS_ENV=test
-
-set -o errexit
-
 dir=$(dirname "$0")
 
 # shellcheck source=./__helping-functions.sh
 source "$dir"/__helping-functions.sh
 
-echo "Running client js tests"
+# ENVS
+export FS_ENV=test
+export CURRENT_USER=$(id -u):$(id -g)
+
+# set -o errexit tells the shell to exit as soon as a command exits with non-zero status, i.e. fails
+set -o errexit
+
+log-header "Running client js tests"
 run-in-container client 'yarn && yarn lint && yarn test'
-
-echo "Done!"
-
